
include $(srctree)/drivers/misc/mediatek/imgsensor/src/Makefile.custom

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/imgsensor/src/$(MTK_PLATFORM)

obj-y	+=  mt_cam_version.o
obj-y	+=  mt_camera_info.o


